### ISSUE TITLE
when js loaded ,  resetBoundariesBtn equals undefined

### ISSUE THREAD

**Issue by dive2Pro** [kauderk/kauderk.github.io#3]
![image](https://user-images.githubusercontent.com/23192045/162013974-4a16afd5-46dc-4ba9-9d6b-64c77c018c88.png)

by the way, thanks for your work!

**Comment by kauderk** [comment]
Currently addressed/solved.
This bug happened because `yt-gif-icon > Miscellaneous > Simulate URL formatter` was turn off. Due to the implementation of "video to url" features `plus sign [+] yt-gif-controls`. In other words: spaghetti code.
[Learn more about them](https://github.com/kauderk/kauderk.github.io/tree/main/yt-gif-extension/install/faq#simulate-url-button-to-video-component)
